2021-12-08 10:05:22 INFO routes.py home[line:15] Enter the home page
2021-12-08 10:05:22 INFO routes.py home[line:15] Enter the home page
2021-12-08 10:05:29 INFO routes.py register[line:24] User try to sign up
2021-12-08 10:22:37 INFO routes.py home[line:15] Enter the home page
2021-12-08 10:22:37 INFO routes.py home[line:15] Enter the home page
2021-12-08 10:22:45 ERROR app.py log_exception[line:1891] Exception on /sort/All [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 96, in soft_products
    else:
KeyError: 3
2021-12-08 10:29:21 INFO routes.py home[line:15] Enter the home page
2021-12-08 10:29:22 INFO routes.py home[line:15] Enter the home page
2021-12-08 10:49:43 INFO routes.py home[line:15] Enter the home page
2021-12-08 10:49:43 INFO routes.py home[line:15] Enter the home page
2021-12-08 10:51:25 INFO routes.py home[line:15] Enter the home page
2021-12-08 10:52:25 INFO routes.py home[line:15] Enter the home page
2021-12-08 10:52:25 INFO routes.py home[line:15] Enter the home page
2021-12-08 10:56:40 INFO routes.py home[line:15] Enter the home page
2021-12-08 10:58:48 INFO routes.py home[line:15] Enter the home page
2021-12-08 10:58:48 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:26:27 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:26:41 INFO routes.py login[line:64] Costumer login
2021-12-08 11:26:41 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:26:44 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:26:47 INFO routes.py category[line:106] category items
2021-12-08 11:26:49 INFO routes.py product[line:123] Successfully query
2021-12-08 11:26:49 INFO routes.py product[line:128] Successfully query
2021-12-08 11:26:52 INFO routes.py product[line:123] Successfully query
2021-12-08 11:26:52 INFO routes.py product[line:128] Successfully query
2021-12-08 11:26:52 INFO routes.py product[line:133] Costumer add products
2021-12-08 11:26:52 INFO routes.py product[line:143] Successfully added items to cart table
2021-12-08 11:26:52 INFO routes.py product[line:150] Adding to shopping cart successfully
2021-12-08 11:26:56 INFO routes.py product_collect[line:179] user add product into Favourite folder
2021-12-08 11:26:56 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:33:06 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:33:06 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:33:09 INFO routes.py category[line:106] category items
2021-12-08 11:33:12 INFO routes.py product[line:123] Successfully query
2021-12-08 11:33:12 INFO routes.py product[line:128] Successfully query
2021-12-08 11:33:16 INFO routes.py product_collect[line:179] user add product into Favourite folder
2021-12-08 11:33:16 INFO routes.py product[line:123] Successfully query
2021-12-08 11:33:16 INFO routes.py product[line:128] Successfully query
2021-12-08 11:33:26 ERROR app.py log_exception[line:1891] Exception on /cart/update [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 348, in update_cart
    for i in session['cart']:
  File "G:\flaskProject\venv\lib\site-packages\werkzeug\local.py", line 378, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
  File "G:\flaskProject\venv\lib\site-packages\flask\sessions.py", line 84, in __getitem__
    return super(SecureCookieSession, self).__getitem__(key)
KeyError: 'cart
2021-12-08 11:33:49 INFO routes.py remove_from_cart[line:330] Successfully delete all product from cart table
2021-12-08 11:43:04 INFO routes.py category[line:106] category items
2021-12-08 11:43:06 INFO routes.py product[line:123] Successfully query
2021-12-08 11:43:06 INFO routes.py product[line:128] Successfully query
2021-12-08 11:43:09 INFO routes.py product[line:123] Successfully query
2021-12-08 11:43:09 INFO routes.py product[line:128] Successfully query
2021-12-08 11:43:09 INFO routes.py product[line:133] Costumer add products
2021-12-08 11:43:09 INFO routes.py product[line:143] Successfully added items to cart table
2021-12-08 11:43:09 INFO routes.py product[line:150] Adding to shopping cart successfully
2021-12-08 11:43:24 ERROR app.py log_exception[line:1891] Exception on /cart/update [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 348, in update_cart
    #     query = request.form.get('query')
  File "G:\flaskProject\venv\lib\site-packages\werkzeug\local.py", line 378, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
  File "G:\flaskProject\venv\lib\site-packages\flask\sessions.py", line 84, in __getitem__
    return super(SecureCookieSession, self).__getitem__(key)
KeyError: 'cart'
2021-12-08 11:48:24 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:48:32 ERROR app.py log_exception[line:1891] Exception on /cart/update/19 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 346, in update_cart
    quantity = int(request.form.get('quantity'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-12-08 11:49:36 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:49:40 ERROR app.py log_exception[line:1891] Exception on /cart [GET]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 236, in cart
    return render_template('cart.html', title='Cart', total=total, total_price=total_price, shipping=shipping,
  File "G:\flaskProject\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "G:\flaskProject\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "G:\flaskProject\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "G:\flaskProject\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "G:\flaskProject\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "G:\flaskProject\apps\../templates\cart.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "G:\flaskProject\apps\../templates\layout.html", line 113, in top-level template code
    {% block content %}{% endblock %}
  File "G:\flaskProject\apps\../templates\cart.html", line 41, in block "content"
    <form id="update" method="POST" action="{{ url_for('update_cart') }}">
  File "G:\flaskProject\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "G:\flaskProject\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'update_cart'. Did you forget to specify values ['product_id']?
2021-12-08 11:49:41 ERROR app.py log_exception[line:1891] Exception on /cart [GET]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 236, in cart
    return render_template('cart.html', title='Cart', total=total, total_price=total_price, shipping=shipping,
  File "G:\flaskProject\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "G:\flaskProject\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "G:\flaskProject\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "G:\flaskProject\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "G:\flaskProject\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "G:\flaskProject\apps\../templates\cart.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "G:\flaskProject\apps\../templates\layout.html", line 113, in top-level template code
    {% block content %}{% endblock %}
  File "G:\flaskProject\apps\../templates\cart.html", line 41, in block "content"
    <form id="update" method="POST" action="{{ url_for('update_cart') }}">
  File "G:\flaskProject\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "G:\flaskProject\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'update_cart'. Did you forget to specify values ['product_id']?
2021-12-08 11:50:26 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:50:26 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:50:33 ERROR app.py log_exception[line:1891] Exception on /cart/update/19 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 346, in update_cart
    quantity = int(request.form.get('quantity'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-12-08 11:50:37 ERROR app.py log_exception[line:1891] Exception on /cart/update/19 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 346, in update_cart
    quantity = int(request.form.get('quantity'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-12-08 11:52:39 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:52:44 ERROR app.py log_exception[line:1891] Exception on /cart/update/19 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 346, in update_cart
    quantity = int(request.form.get('quantity'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-12-08 11:53:47 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:53:53 ERROR app.py log_exception[line:1891] Exception on /cart/update/19 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 346, in update_cart
    quantity = int(request.form.get('update_num'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-12-08 11:56:17 INFO routes.py home[line:15] Enter the home page
2021-12-08 11:56:23 ERROR app.py log_exception[line:1891] Exception on /cart/update/19 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 346, in update_cart
    quantity = int(request.form.get('update_num'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-12-08 11:56:28 ERROR app.py log_exception[line:1891] Exception on /cart/update/19 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 346, in update_cart
    quantity = int(request.form.get('update_num'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-12-08 12:00:38 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:00:38 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:00:46 ERROR app.py log_exception[line:1891] Exception on /cart/update/19 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 348, in update_cart
    cart_item.quantity = quantity
AttributeError: 'NoneType' object has no attribute 'quantity'
2021-12-08 12:00:58 ERROR app.py log_exception[line:1891] Exception on /cart/update/19 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 348, in update_cart
    cart_item.quantity = quantity
AttributeError: 'NoneType' object has no attribute 'quantity'
2021-12-08 12:03:24 INFO routes.py category[line:106] category items
2021-12-08 12:03:26 INFO routes.py product[line:123] Successfully query
2021-12-08 12:03:26 INFO routes.py product[line:128] Successfully query
2021-12-08 12:03:29 INFO routes.py product[line:123] Successfully query
2021-12-08 12:03:29 INFO routes.py product[line:128] Successfully query
2021-12-08 12:03:30 INFO routes.py product[line:133] Costumer add products
2021-12-08 12:03:30 INFO routes.py product[line:150] Adding to shopping cart successfully
2021-12-08 12:03:38 ERROR app.py log_exception[line:1891] Exception on /cart/update/19 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 348, in update_cart
    cart_item.quantity = quantity
AttributeError: 'NoneType' object has no attribute 'quantity'
2021-12-08 12:06:26 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:06:26 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:07:14 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:07:14 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:07:30 ERROR app.py log_exception[line:1891] Exception on /cart/update/19 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 348, in update_cart
    cart_item.quantity += quantity
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2021-12-08 12:07:30 ERROR app.py log_exception[line:1891] Exception on /cart/update/19 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 348, in update_cart
    cart_item.quantity += quantity
TypeError: unsupported operand type(s) for +=: 'int' and 'str'
2021-12-08 12:08:09 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:08:09 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:09:25 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:10:03 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:11:21 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:11:21 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:11:50 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:11:52 INFO routes.py category[line:106] category items
2021-12-08 12:11:55 INFO routes.py product[line:123] Successfully query
2021-12-08 12:11:55 INFO routes.py product[line:128] Successfully query
2021-12-08 12:11:57 INFO routes.py product[line:123] Successfully query
2021-12-08 12:11:57 INFO routes.py product[line:128] Successfully query
2021-12-08 12:11:57 INFO routes.py product[line:133] Costumer add products
2021-12-08 12:11:57 INFO routes.py product[line:143] Successfully added items to cart table
2021-12-08 12:11:57 INFO routes.py product[line:150] Adding to shopping cart successfully
2021-12-08 12:12:18 INFO routes.py checkout[line:267] Successfully added information to info table
2021-12-08 12:12:18 INFO routes.py checkout[line:278] Successfully added product to cart_item table
2021-12-08 12:12:18 INFO routes.py checkout[line:285] Successfully delete product from cart table
2021-12-08 12:12:18 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:12:29 INFO routes.py logout[line:374] logout
2021-12-08 12:12:29 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:12:37 INFO routes.py login[line:61] Seller login
2021-12-08 12:16:46 INFO routes.py seller_add[line:477] seller add the product
2021-12-08 12:17:48 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:17:52 INFO routes.py logout[line:374] logout
2021-12-08 12:17:52 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:18:02 INFO routes.py login[line:61] Seller login
2021-12-08 12:18:28 ERROR app.py log_exception[line:1891] Exception on /seller_edit/31 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 446, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-08 12:23:17 INFO routes.py seller_edit[line:450] seller edit the product
2021-12-08 12:23:17 INFO routes.py seller_edit[line:451] Successful modification of database information
2021-12-08 12:23:25 INFO routes.py seller_edit[line:450] seller edit the product
2021-12-08 12:23:25 INFO routes.py seller_edit[line:451] Successful modification of database information
2021-12-08 12:23:49 INFO routes.py seller_edit[line:450] seller edit the product
2021-12-08 12:23:49 INFO routes.py seller_edit[line:451] Successful modification of database information
2021-12-08 12:23:55 INFO routes.py seller_delete[line:428] seller delete the product
2021-12-08 12:24:11 INFO routes.py seller_add[line:478] seller add the product
2021-12-08 12:24:18 INFO routes.py seller_delete[line:428] seller delete the product
2021-12-08 12:24:38 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:24:43 INFO routes.py logout[line:374] logout
2021-12-08 12:24:43 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:24:50 INFO routes.py home[line:15] Enter the home page
2021-12-08 12:24:59 INFO routes.py home[line:15] Enter the home page
2021-12-08 14:43:41 INFO routes.py home[line:15] Enter the home page
2021-12-08 14:43:41 INFO routes.py home[line:15] Enter the home page
2021-12-08 14:43:52 INFO routes.py home[line:15] Enter the home page
2021-12-08 14:44:05 INFO routes.py login[line:64] Costumer login
2021-12-08 14:44:05 INFO routes.py home[line:15] Enter the home page
2021-12-08 15:18:25 INFO routes.py home[line:15] Enter the home page
2021-12-08 15:18:25 INFO routes.py home[line:15] Enter the home page
2021-12-08 15:19:04 INFO routes.py category[line:106] category items
2021-12-08 15:19:14 INFO routes.py category[line:106] category items
2021-12-08 15:23:38 INFO routes.py home[line:15] Enter the home page
2021-12-08 15:29:48 INFO routes.py category[line:106] category items
2021-12-08 15:30:18 INFO routes.py category[line:106] category items
2021-12-08 15:30:24 INFO routes.py category[line:106] category items
2021-12-08 15:30:31 INFO routes.py category[line:106] category items
2021-12-08 15:30:34 INFO routes.py category[line:106] category items
2021-12-08 15:30:39 INFO routes.py product[line:123] Successfully query
2021-12-08 15:30:39 INFO routes.py product[line:128] Successfully query
2021-12-08 15:31:36 INFO routes.py product[line:123] Successfully query
2021-12-08 15:31:36 INFO routes.py product[line:128] Successfully query
2021-12-08 15:34:23 INFO routes.py product[line:123] Successfully query
2021-12-08 15:34:23 INFO routes.py product[line:128] Successfully query
2021-12-08 15:34:42 INFO routes.py product[line:123] Successfully query
2021-12-08 15:34:42 INFO routes.py product[line:128] Successfully query
2021-12-08 15:34:48 INFO routes.py category[line:106] category items
2021-12-08 15:34:49 INFO routes.py category[line:106] category items
2021-12-08 15:34:49 INFO routes.py home[line:15] Enter the home page
2021-12-08 15:34:49 INFO routes.py category[line:106] category items
2021-12-08 15:35:28 INFO routes.py home[line:15] Enter the home page
2021-12-08 15:35:33 INFO routes.py home[line:15] Enter the home page
2021-12-08 15:35:43 INFO routes.py login[line:64] Costumer login
2021-12-08 15:35:43 INFO routes.py home[line:15] Enter the home page
2021-12-08 16:38:51 INFO routes.py category[line:106] category items
2021-12-08 16:38:56 INFO routes.py product[line:123] Successfully query
2021-12-08 16:38:56 INFO routes.py product[line:128] Successfully query
2021-12-08 16:47:04 INFO routes.py product[line:123] Successfully query
2021-12-08 16:47:04 INFO routes.py product[line:128] Successfully query
2021-12-08 16:47:18 INFO routes.py category[line:106] category items
2021-12-08 16:47:25 INFO routes.py category[line:106] category items
2021-12-08 16:47:31 INFO routes.py product[line:123] Successfully query
2021-12-08 16:47:31 INFO routes.py product[line:128] Successfully query
2021-12-08 16:54:37 INFO routes.py category[line:106] category items
2021-12-08 16:54:42 INFO routes.py product[line:123] Successfully query
2021-12-08 16:54:42 INFO routes.py product[line:128] Successfully query
2021-12-08 18:26:50 INFO routes.py home[line:15] Enter the home page
2021-12-08 18:26:54 INFO routes.py category[line:106] category items
2021-12-08 18:26:59 INFO routes.py category[line:106] category items
2021-12-08 18:27:07 INFO routes.py category[line:106] category items
2021-12-08 18:27:10 INFO routes.py product[line:123] Successfully query
2021-12-08 18:27:10 INFO routes.py product[line:128] Successfully query
2021-12-08 18:29:50 INFO routes.py login[line:64] Costumer login
2021-12-08 18:29:50 INFO routes.py home[line:15] Enter the home page
2021-12-08 18:29:54 INFO routes.py category[line:106] category items
2021-12-08 18:30:00 INFO routes.py category[line:106] category items
2021-12-08 18:30:03 INFO routes.py category[line:106] category items
2021-12-08 18:30:05 INFO routes.py product[line:123] Successfully query
2021-12-08 18:30:05 INFO routes.py product[line:128] Successfully query
2021-12-08 18:30:12 INFO routes.py new_comment[line:215] Successfully added new comment to comment table
2021-12-08 18:30:12 INFO routes.py product[line:123] Successfully query
2021-12-08 18:30:12 INFO routes.py product[line:128] Successfully query
2021-12-08 18:31:57 INFO routes.py product[line:123] Successfully query
2021-12-08 18:31:57 INFO routes.py product[line:128] Successfully query
2021-12-08 18:31:57 INFO routes.py product[line:133] Costumer add products
2021-12-08 18:31:57 INFO routes.py product[line:143] Successfully added items to cart table
2021-12-08 18:31:57 INFO routes.py product[line:150] Adding to shopping cart successfully
2021-12-08 18:36:57 INFO routes.py checkout[line:267] Successfully added information to info table
2021-12-08 18:36:57 INFO routes.py checkout[line:278] Successfully added product to cart_item table
2021-12-08 18:36:57 INFO routes.py checkout[line:285] Successfully delete product from cart table
2021-12-08 18:36:57 INFO routes.py home[line:15] Enter the home page
2021-12-08 18:42:40 INFO routes.py logout[line:374] logout
2021-12-08 18:42:40 INFO routes.py home[line:15] Enter the home page
2021-12-08 18:42:51 INFO routes.py login[line:61] Seller login
2021-12-08 18:52:43 INFO routes.py login[line:64] Costumer login
2021-12-08 18:52:43 INFO routes.py home[line:15] Enter the home page
2021-12-08 19:08:51 INFO routes.py logout[line:374] logout
2021-12-08 19:08:51 INFO routes.py home[line:15] Enter the home page
2021-12-08 19:08:59 INFO routes.py login[line:61] Seller login
2021-12-08 19:10:21 INFO routes.py reject[line:544] Refusal to return a product to a user
2021-12-08 20:28:11 INFO routes.py home[line:15] Enter the home page
2021-12-08 23:06:19 INFO routes.py home[line:15] Enter the home page
2021-12-08 23:32:32 INFO routes.py home[line:15] Enter the home page
2021-12-08 23:33:20 INFO routes.py home[line:15] Enter the home page
2021-12-08 23:34:51 INFO routes.py category[line:111] category items
2021-12-08 23:35:03 INFO routes.py category[line:111] category items
2021-12-08 23:35:09 INFO routes.py category[line:111] category items
2021-12-08 23:35:12 INFO routes.py product[line:128] Successfully query Nike Sportswear Swoosh
2021-12-08 23:35:12 INFO routes.py product[line:133] Successfully query
2021-12-08 23:35:28 INFO routes.py login[line:66] 321 login
2021-12-09 00:29:17 INFO routes.py logout[line:379] logout
2021-12-09 00:29:17 INFO routes.py home[line:15] Enter the home page
2021-12-09 00:30:22 INFO routes.py logout[line:379] logout
2021-12-09 00:30:22 INFO routes.py home[line:15] Enter the home page
2021-12-09 00:30:57 INFO routes.py logout[line:379] logout
2021-12-09 00:30:57 INFO routes.py home[line:15] Enter the home page
2021-12-09 00:36:45 INFO routes.py logout[line:379] logout
2021-12-09 00:36:45 INFO routes.py home[line:15] Enter the home page
2021-12-09 00:38:53 INFO routes.py logout[line:379] logout
2021-12-09 00:38:53 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:00:33 INFO routes.py logout[line:379] logout
2021-12-09 01:00:33 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:01:08 INFO routes.py logout[line:379] logout
2021-12-09 01:01:08 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:01:38 INFO routes.py register[line:25] User try to sign up
2021-12-09 01:02:01 INFO routes.py logout[line:379] logout
2021-12-09 01:02:01 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:02:01 INFO routes.py logout[line:379] logout
2021-12-09 01:02:01 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:05:00 INFO routes.py logout[line:379] logout
2021-12-09 01:05:00 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:05:00 INFO routes.py logout[line:379] logout
2021-12-09 01:05:00 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:07:28 INFO routes.py register[line:25] User try to sign up
2021-12-09 01:07:41 INFO routes.py logout[line:379] logout
2021-12-09 01:07:41 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:12:17 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:14:55 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:14:55 INFO routes.py logout[line:379] logout
2021-12-09 01:14:55 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:14:55 INFO routes.py logout[line:379] logout
2021-12-09 01:14:55 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:16:35 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:16:51 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:17:14 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:17:21 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:17:21 INFO routes.py logout[line:379] logout
2021-12-09 01:17:21 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:17:21 INFO routes.py logout[line:379] logout
2021-12-09 01:17:21 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:17:26 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:17:26 INFO routes.py logout[line:379] logout
2021-12-09 01:17:26 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:17:26 INFO routes.py logout[line:379] logout
2021-12-09 01:17:26 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:20:36 ERROR app.py log_exception[line:1891] Exception on /seller_edit/30 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:20:36 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:20:36 INFO routes.py logout[line:379] logout
2021-12-09 01:20:36 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:20:36 INFO routes.py logout[line:379] logout
2021-12-09 01:20:36 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:22:02 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:22:09 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:22:19 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:22:25 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:22:31 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:22:40 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:23:13 INFO routes.py logout[line:379] logout
2021-12-09 01:23:13 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:23:13 INFO routes.py logout[line:379] logout
2021-12-09 01:23:13 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:23:46 ERROR app.py log_exception[line:1891] Exception on /seller_edit/30 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:23:46 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:23:46 INFO routes.py logout[line:379] logout
2021-12-09 01:23:46 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:23:46 INFO routes.py logout[line:379] logout
2021-12-09 01:23:46 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:24:26 INFO routes.py seller_delete[line:433] seller delete the product
2021-12-09 01:24:26 ERROR app.py log_exception[line:1891] Exception on /seller_edit/2 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 451, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-09 01:24:26 INFO routes.py logout[line:379] logout
2021-12-09 01:24:26 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:24:45 ERROR app.py log_exception[line:1891] Exception on /seller_delete/30 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2634, in delete
    state = attributes.instance_state(instance)
AttributeError: 'NoneType' object has no attribute '_sa_instance_state'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 431, in seller_delete
    db.session.delete(product)
  File "<string>", line 2, in delete
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2636, in delete
    util.raise_(
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped
2021-12-09 01:24:45 INFO routes.py logout[line:379] logout
2021-12-09 01:24:45 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:25:51 ERROR app.py log_exception[line:1891] Exception on /seller_delete/30 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2634, in delete
    state = attributes.instance_state(instance)
AttributeError: 'NoneType' object has no attribute '_sa_instance_state'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 431, in seller_delete
    db.session.delete(product)
  File "<string>", line 2, in delete
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2636, in delete
    util.raise_(
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped
2021-12-09 01:26:37 INFO routes.py seller_delete[line:433] seller delete the product
2021-12-09 01:26:37 INFO routes.py logout[line:379] logout
2021-12-09 01:26:37 INFO routes.py home[line:15] Enter the home page
2021-12-09 01:43:38 INFO routes.py home[line:15] Enter the home page
2021-12-17 10:36:47 ERROR app.py log_exception[line:1891] Exception on /seller_delete/30 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2634, in delete
    state = attributes.instance_state(instance)
AttributeError: 'NoneType' object has no attribute '_sa_instance_state'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 432, in seller_delete
    db.session.delete(product)
  File "<string>", line 2, in delete
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2636, in delete
    util.raise_(
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped
2021-12-17 10:37:03 INFO routes.py logout[line:380] logout
2021-12-17 10:37:03 INFO routes.py home[line:16] Enter the home page
2021-12-17 10:37:14 INFO routes.py register[line:26] User try to sign up
2021-12-17 10:37:44 INFO routes.py logout[line:380] logout
2021-12-17 10:37:44 INFO routes.py home[line:16] Enter the home page
2021-12-17 10:55:42 INFO routes.py logout[line:380] logout
2021-12-17 10:55:42 INFO routes.py home[line:16] Enter the home page
2021-12-17 10:55:43 INFO routes.py logout[line:380] logout
2021-12-17 10:55:43 INFO routes.py home[line:16] Enter the home page
2021-12-17 11:24:07 INFO routes.py seller_delete[line:434] seller delete the product
2021-12-17 11:24:29 ERROR app.py log_exception[line:1891] Exception on /seller_delete/31 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2634, in delete
    state = attributes.instance_state(instance)
AttributeError: 'NoneType' object has no attribute '_sa_instance_state'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 432, in seller_delete
    db.session.delete(product)
  File "<string>", line 2, in delete
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2636, in delete
    util.raise_(
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped
2021-12-17 11:24:38 ERROR app.py log_exception[line:1891] Exception on /seller_delete/31 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2634, in delete
    state = attributes.instance_state(instance)
AttributeError: 'NoneType' object has no attribute '_sa_instance_state'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 432, in seller_delete
    db.session.delete(product)
  File "<string>", line 2, in delete
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2636, in delete
    util.raise_(
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped
2021-12-17 11:24:59 INFO routes.py seller_delete[line:434] seller delete the product
2021-12-17 11:37:01 ERROR app.py log_exception[line:1891] Exception on /seller_edit/30 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 452, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-17 11:37:42 ERROR app.py log_exception[line:1891] Exception on /seller_edit/30 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 452, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-17 11:38:09 ERROR app.py log_exception[line:1891] Exception on /seller_edit/30 [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 452, in seller_edit
    product.image_file = photos.save(form.photo.data)
  File "G:\flaskProject\venv\lib\site-packages\flask_uploads.py", line 402, in save
    raise TypeError("storage must be a werkzeug.FileStorage")
TypeError: storage must be a werkzeug.FileStorage
2021-12-18 10:23:35 INFO routes.py logout[line:380] logout
2021-12-18 10:23:35 INFO routes.py home[line:16] Enter the home page
2021-12-18 10:23:35 INFO routes.py logout[line:380] logout
2021-12-18 10:23:35 INFO routes.py home[line:16] Enter the home page
2021-12-18 10:24:44 INFO routes.py logout[line:380] logout
2021-12-18 10:24:44 INFO routes.py home[line:16] Enter the home page
2021-12-18 10:24:44 INFO routes.py logout[line:380] logout
2021-12-18 10:24:44 INFO routes.py home[line:16] Enter the home page
2021-12-18 10:26:41 INFO routes.py seller_delete[line:434] seller delete the product
2021-12-18 10:26:41 INFO routes.py logout[line:380] logout
2021-12-18 10:26:41 INFO routes.py home[line:16] Enter the home page
2021-12-18 10:26:41 INFO routes.py logout[line:380] logout
2021-12-18 10:26:41 INFO routes.py home[line:16] Enter the home page
2021-12-18 10:48:47 INFO routes.py logout[line:380] logout
2021-12-18 10:48:47 INFO routes.py home[line:16] Enter the home page
2021-12-18 10:49:12 INFO routes.py logout[line:380] logout
2021-12-18 10:49:12 INFO routes.py home[line:16] Enter the home page
2021-12-18 11:00:35 INFO routes.py product[line:129] Successfully query test
2021-12-18 11:00:35 INFO routes.py product[line:134] Successfully query
2021-12-18 11:13:33 INFO routes.py product[line:129] Successfully query test
2021-12-18 11:13:33 INFO routes.py product[line:134] Successfully query
2021-12-18 11:20:37 INFO routes.py product[line:129] Successfully query test
2021-12-18 11:20:37 INFO routes.py product[line:134] Successfully query
2021-12-18 11:20:37 INFO routes.py product[line:129] Successfully query test
2021-12-18 11:20:37 INFO routes.py product[line:134] Successfully query
2021-12-18 11:20:52 INFO routes.py product[line:129] Successfully query test
2021-12-18 11:20:52 INFO routes.py product[line:134] Successfully query
2021-12-18 11:20:52 INFO routes.py product[line:129] Successfully query test
2021-12-18 11:20:52 INFO routes.py product[line:134] Successfully query
2021-12-18 11:21:14 INFO routes.py product[line:129] Successfully query test
2021-12-18 11:21:14 INFO routes.py product[line:134] Successfully query
2021-12-18 11:21:14 INFO routes.py product[line:129] Successfully query test
2021-12-18 11:21:14 INFO routes.py product[line:134] Successfully query
2021-12-18 11:21:21 INFO routes.py product[line:129] Successfully query test
2021-12-18 11:21:21 INFO routes.py product[line:134] Successfully query
2021-12-18 11:21:22 INFO routes.py product[line:129] Successfully query test
2021-12-18 11:21:22 INFO routes.py product[line:134] Successfully query
2021-12-18 12:19:32 INFO routes.py product[line:129] Successfully query test
2021-12-18 12:19:32 INFO routes.py product[line:134] Successfully query
2021-12-18 12:19:32 INFO routes.py product[line:129] Successfully query test
2021-12-18 12:19:32 INFO routes.py product[line:134] Successfully query
2021-12-18 12:19:33 INFO routes.py logout[line:380] logout
2021-12-18 12:19:33 INFO routes.py home[line:16] Enter the home page
2021-12-18 12:19:53 INFO routes.py product[line:129] Successfully query test
2021-12-18 12:19:53 INFO routes.py product[line:134] Successfully query
2021-12-18 12:19:53 INFO routes.py product[line:129] Successfully query test
2021-12-18 12:19:53 INFO routes.py product[line:134] Successfully query
2021-12-18 12:19:53 INFO routes.py logout[line:380] logout
2021-12-18 12:19:53 INFO routes.py home[line:16] Enter the home page
2021-12-18 13:28:02 INFO routes.py home[line:16] Enter the home page
2021-12-18 13:28:03 INFO routes.py home[line:16] Enter the home page
2021-12-18 13:28:14 ERROR app.py log_exception[line:1891] Exception on /reset_password [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 568, in reset_request
    send_rest_email(user)
  File "G:\flaskProject\apps\routes.py", line 554, in send_rest_email
    token = user.get_reset_token()
  File "G:\flaskProject\apps\models.py", line 33, in get_reset_token
    s = Serializer(current_app.config['SECRET_KEY'], expires_sec)
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\ext\serializer.py", line 76, in Serializer
    pickler = pickle.Pickler(*args, **kw)
TypeError: file must have a 'write' attribute
2021-12-18 15:27:58 INFO routes.py home[line:16] Enter the home page
2021-12-18 15:28:08 ERROR app.py log_exception[line:1891] Exception on /reset_password [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 568, in reset_request
    send_rest_email(user)
  File "G:\flaskProject\apps\routes.py", line 554, in send_rest_email
    token = user.get_reset_token()
  File "G:\flaskProject\apps\models.py", line 33, in get_reset_token
    s = Serializer(app.config['SECRET_KEY'], expires_sec)
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\ext\serializer.py", line 76, in Serializer
    pickler = pickle.Pickler(*args, **kw)
ValueError: pickle protocol must be <= 5
2021-12-19 13:04:36 INFO routes.py home[line:16] Enter the home page
2021-12-19 13:04:48 INFO routes.py category[line:111] category items
2021-12-19 13:05:05 INFO routes.py login[line:69] 123 login
2021-12-19 13:05:05 INFO routes.py home[line:16] Enter the home page
2021-12-19 13:05:11 INFO routes.py logout[line:379] logout
2021-12-19 13:05:11 INFO routes.py home[line:16] Enter the home page
2021-12-19 13:05:26 ERROR app.py log_exception[line:1891] Exception on /reset_password [POST]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 568, in reset_request
    send_rest_email(user)
  File "G:\flaskProject\apps\routes.py", line 554, in send_rest_email
    token = user.get_reset_token()
  File "G:\flaskProject\apps\models.py", line 33, in get_reset_token
    s = Serializer(app.config['SECRET_KEY'], expires_sec)
  File "G:\flaskProject\venv\lib\site-packages\sqlalchemy\ext\serializer.py", line 76, in Serializer
    pickler = pickle.Pickler(*args, **kw)
ValueError: pickle protocol must be <= 5
2021-12-19 15:46:26 INFO routes.py home[line:16] Enter the home page
2021-12-19 15:57:21 INFO routes.py category[line:111] category items
2021-12-19 15:57:24 INFO routes.py product[line:128] Successfully query test
2021-12-19 15:57:24 INFO routes.py product[line:133] Successfully query
2021-12-19 15:57:42 INFO routes.py product[line:128] Successfully query test
2021-12-19 15:57:42 INFO routes.py product[line:133] Successfully query
2021-12-19 15:57:49 INFO routes.py product[line:128] Successfully query test
2021-12-19 15:57:49 INFO routes.py product[line:133] Successfully query
2021-12-19 15:58:00 INFO routes.py product[line:128] Successfully query test
2021-12-19 15:58:00 INFO routes.py product[line:133] Successfully query
2021-12-19 15:58:39 INFO routes.py product[line:128] Successfully query test
2021-12-19 15:58:39 INFO routes.py product[line:133] Successfully query
2021-12-19 15:58:50 INFO routes.py login[line:69] 123 login
2021-12-19 15:58:50 INFO routes.py home[line:16] Enter the home page
2021-12-19 15:58:56 INFO routes.py category[line:111] category items
2021-12-19 15:58:58 INFO routes.py product[line:128] Successfully query Nike Blazer Mid '77 Jumbo
2021-12-19 15:58:58 INFO routes.py product[line:133] Successfully query
2021-12-19 15:59:01 INFO routes.py product[line:128] Successfully query Nike Blazer Mid '77 Jumbo
2021-12-19 15:59:01 INFO routes.py product[line:133] Successfully query
2021-12-19 15:59:01 INFO routes.py product[line:138] 123 add products
2021-12-19 15:59:01 INFO routes.py product[line:148] Successfully added items to cart table
2021-12-19 15:59:01 INFO routes.py product[line:155] 123 add product to shopping cart successfully
2021-12-19 15:59:13 INFO routes.py product[line:128] Successfully query Nike Blazer Mid '77 Jumbo
2021-12-19 15:59:13 INFO routes.py product[line:133] Successfully query
2021-12-19 15:59:13 INFO routes.py product[line:138] 123 add products
2021-12-19 15:59:13 INFO routes.py product[line:155] 123 add product to shopping cart successfully
2021-12-19 15:59:40 INFO routes.py checkout[line:272] Successfully added information to info table
2021-12-19 15:59:40 INFO routes.py checkout[line:283] Successfully added product to cart_item table
2021-12-19 15:59:40 INFO routes.py checkout[line:290] Successfully delete product from cart table
2021-12-19 15:59:40 INFO routes.py home[line:16] Enter the home page
2021-12-19 16:00:22 INFO routes.py home[line:16] Enter the home page
2021-12-19 16:00:22 INFO routes.py home[line:16] Enter the home page
2021-12-19 16:00:39 ERROR app.py log_exception[line:1891] Exception on /order [GET]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 323, in order
    return render_template('orders.html', history_order=history_order)
  File "G:\flaskProject\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "G:\flaskProject\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "G:\flaskProject\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "G:\flaskProject\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "G:\flaskProject\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "G:\flaskProject\apps\../templates\orders.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "G:\flaskProject\apps\../templates\layout.html", line 109, in top-level template code
    {% block content %}{% endblock %}
  File "G:\flaskProject\apps\../templates\orders.html", line 68, in block "content"
    <form action="{{ url_for('return_item', product_id = history_order[key][10]) }}" method="POST">
  File "G:\flaskProject\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "G:\flaskProject\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'return_item' with values ['product_id']. Did you forget to specify values ['id']?
2021-12-19 16:00:43 ERROR app.py log_exception[line:1891] Exception on /order [GET]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 323, in order
    return render_template('orders.html', history_order=history_order)
  File "G:\flaskProject\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "G:\flaskProject\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "G:\flaskProject\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "G:\flaskProject\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "G:\flaskProject\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "G:\flaskProject\apps\../templates\orders.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "G:\flaskProject\apps\../templates\layout.html", line 109, in top-level template code
    {% block content %}{% endblock %}
  File "G:\flaskProject\apps\../templates\orders.html", line 68, in block "content"
    <form action="{{ url_for('return_item', product_id = history_order[key][10]) }}" method="POST">
  File "G:\flaskProject\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "G:\flaskProject\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'return_item' with values ['product_id']. Did you forget to specify values ['id']?
2021-12-19 17:01:24 INFO routes.py home[line:16] Enter the home page
2021-12-19 17:01:24 INFO routes.py home[line:16] Enter the home page
2021-12-19 17:01:33 INFO routes.py login[line:69] 123 login
2021-12-19 17:01:33 INFO routes.py home[line:16] Enter the home page
2021-12-19 17:04:48 INFO routes.py home[line:16] Enter the home page
2021-12-19 17:04:48 INFO routes.py home[line:16] Enter the home page
2021-12-20 11:18:42 INFO routes.py home[line:16] Enter the home page
2021-12-20 11:18:42 INFO routes.py home[line:16] Enter the home page
2021-12-20 11:18:55 INFO routes.py login[line:67] 123 login
2021-12-20 11:18:55 INFO routes.py home[line:16] Enter the home page
2021-12-20 11:19:03 INFO routes.py home[line:16] Enter the home page
2021-12-20 11:19:08 INFO routes.py category[line:98] category items
2021-12-20 11:19:11 INFO routes.py product[line:115] Successfully query test
2021-12-20 11:19:11 INFO routes.py product[line:120] Successfully query
2021-12-20 11:19:11 ERROR app.py log_exception[line:1891] Exception on /product/30 [GET]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 160, in product
    return render_template('product.html', title='Product', product=product, random_itemid=random_itemid,
  File "G:\flaskProject\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "G:\flaskProject\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "G:\flaskProject\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "G:\flaskProject\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "G:\flaskProject\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "G:\flaskProject\apps\../templates\product.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "G:\flaskProject\apps\../templates\layout.html", line 109, in top-level template code
    {% block content %}{% endblock %}
  File "G:\flaskProject\apps\../templates\product.html", line 67, in block "content"
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
jinja2.exceptions.UndefinedError: 'csrf_token' is undefined
2021-12-20 11:19:12 INFO routes.py category[line:98] category items
2021-12-20 11:19:14 INFO routes.py product[line:115] Successfully query Nike ZoomX Vaporfly Next% 2
2021-12-20 11:19:14 INFO routes.py product[line:120] Successfully query
2021-12-20 11:19:14 ERROR app.py log_exception[line:1891] Exception on /product/19 [GET]
Traceback (most recent call last):
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "G:\flaskProject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "G:\flaskProject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\flaskProject\apps\routes.py", line 160, in product
    return render_template('product.html', title='Product', product=product, random_itemid=random_itemid,
  File "G:\flaskProject\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "G:\flaskProject\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "G:\flaskProject\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "G:\flaskProject\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "G:\flaskProject\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "G:\flaskProject\apps\../templates\product.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "G:\flaskProject\apps\../templates\layout.html", line 109, in top-level template code
    {% block content %}{% endblock %}
  File "G:\flaskProject\apps\../templates\product.html", line 67, in block "content"
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
jinja2.exceptions.UndefinedError: 'csrf_token' is undefined
2021-12-20 11:19:15 INFO routes.py category[line:98] category items
2021-12-20 11:20:42 INFO routes.py home[line:16] Enter the home page
2021-12-20 11:20:42 INFO routes.py home[line:16] Enter the home page
2021-12-20 11:20:48 INFO routes.py category[line:98] category items
2021-12-20 11:20:50 INFO routes.py product[line:115] Successfully query test
2021-12-20 11:20:50 INFO routes.py product[line:120] Successfully query
2021-12-20 11:21:00 INFO routes.py product[line:115] Successfully query test
2021-12-20 11:21:00 INFO routes.py product[line:120] Successfully query
2021-12-20 11:21:00 INFO routes.py product[line:125] 123 add products
2021-12-20 11:21:00 INFO routes.py product[line:135] Successfully added items to cart table
2021-12-20 11:21:00 INFO routes.py product[line:142] 123 add product to shopping cart successfully
2021-12-20 11:37:44 INFO routes.py category[line:98] category items
2021-12-20 11:37:47 INFO routes.py product[line:115] Successfully query Nike Therma-FIT ADV ACG“Lunar Lake”
2021-12-20 11:37:47 INFO routes.py product[line:120] Successfully query
2021-12-20 11:40:04 INFO routes.py home[line:16] Enter the home page
2021-12-20 11:40:09 INFO routes.py category[line:98] category items
2021-12-20 11:40:11 INFO routes.py product[line:115] Successfully query Nike ZoomX Vaporfly Next% 2
2021-12-20 11:40:11 INFO routes.py product[line:120] Successfully query
2021-12-20 13:23:58 INFO routes.py seller_delete[line:395] seller delete the product
2021-12-20 13:23:58 INFO routes.py logout[line:344] logout
2021-12-20 13:23:58 INFO routes.py home[line:16] Enter the home page
2021-12-20 13:23:58 INFO routes.py logout[line:344] logout
2021-12-20 13:23:58 INFO routes.py home[line:16] Enter the home page
2021-12-20 13:23:58 INFO routes.py product[line:115] Successfully query test
2021-12-20 13:23:58 INFO routes.py product[line:120] Successfully query
2021-12-20 13:23:58 INFO routes.py product[line:115] Successfully query test
2021-12-20 13:23:58 INFO routes.py product[line:120] Successfully query
2021-12-20 13:23:59 INFO routes.py logout[line:344] logout
2021-12-20 13:23:59 INFO routes.py home[line:16] Enter the home page
2021-12-20 13:24:55 INFO routes.py seller_delete[line:395] seller delete the product
2021-12-20 13:24:55 INFO routes.py logout[line:344] logout
2021-12-20 13:24:55 INFO routes.py home[line:16] Enter the home page
2021-12-20 13:24:56 INFO routes.py logout[line:344] logout
2021-12-20 13:24:56 INFO routes.py home[line:16] Enter the home page
2021-12-20 13:24:56 INFO routes.py product[line:115] Successfully query test
2021-12-20 13:24:56 INFO routes.py product[line:120] Successfully query
2021-12-20 13:24:56 INFO routes.py product[line:115] Successfully query test
2021-12-20 13:24:56 INFO routes.py product[line:120] Successfully query
2021-12-20 13:24:56 INFO routes.py logout[line:344] logout
2021-12-20 13:24:56 INFO routes.py home[line:16] Enter the home page
2021-12-20 13:27:42 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:28:12 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:29:05 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:29:05 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:29:56 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:29:56 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:30:05 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:30:05 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:31:17 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:31:17 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:31:46 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:31:46 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:32:52 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:32:52 INFO routes.py register[line:25] User try to sign up
2021-12-20 13:43:40 INFO routes.py login[line:67] 123 login
2021-12-20 13:43:40 INFO routes.py home[line:16] Enter the home page
2021-12-20 13:43:56 INFO routes.py user[line:361] Successful modification of database information
2021-12-20 14:55:20 INFO routes.py register[line:25] User try to sign up
2021-12-20 14:55:20 INFO routes.py register[line:25] User try to sign up
2021-12-20 14:55:26 INFO routes.py seller_delete[line:395] seller delete the product
2021-12-20 14:55:26 INFO routes.py logout[line:344] logout
2021-12-20 14:55:26 INFO routes.py home[line:16] Enter the home page
2021-12-20 14:55:26 INFO routes.py register[line:25] User try to sign up
2021-12-20 14:55:27 INFO routes.py register[line:25] User try to sign up
2021-12-20 14:55:27 INFO routes.py logout[line:344] logout
2021-12-20 14:55:27 INFO routes.py home[line:16] Enter the home page
2021-12-20 14:55:27 INFO routes.py register[line:25] User try to sign up
2021-12-20 14:55:27 INFO routes.py register[line:25] User try to sign up
2021-12-20 14:55:27 INFO routes.py product[line:115] Successfully query test
2021-12-20 14:55:27 INFO routes.py product[line:120] Successfully query
2021-12-20 14:55:27 INFO routes.py product[line:115] Successfully query test
2021-12-20 14:55:27 INFO routes.py product[line:120] Successfully query
2021-12-20 14:55:27 INFO routes.py logout[line:344] logout
2021-12-20 14:55:27 INFO routes.py home[line:16] Enter the home page
2021-12-20 14:55:27 INFO routes.py register[line:25] User try to sign up
2021-12-20 14:55:27 INFO routes.py register[line:25] User try to sign up
2021-12-20 15:11:46 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:11:46 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:11:56 INFO routes.py login[line:67] 12 login
2021-12-20 15:11:56 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:12:01 INFO routes.py category[line:98] category items
2021-12-20 15:12:03 INFO routes.py product[line:115] Successfully query Nike ZoomX Vaporfly Next% 2
2021-12-20 15:12:03 INFO routes.py product[line:120] Successfully query
2021-12-20 15:12:06 INFO routes.py product[line:115] Successfully query Nike ZoomX Vaporfly Next% 2
2021-12-20 15:12:06 INFO routes.py product[line:120] Successfully query
2021-12-20 15:12:06 INFO routes.py product[line:125] 12 add products
2021-12-20 15:12:06 INFO routes.py product[line:135] Successfully added items to cart table
2021-12-20 15:12:06 INFO routes.py product[line:142] 12 add product to shopping cart successfully
2021-12-20 15:12:09 INFO routes.py product_collect[line:170] 12 add product into Favourite folder
2021-12-20 15:12:09 INFO routes.py product[line:115] Successfully query Nike ZoomX Vaporfly Next% 2
2021-12-20 15:12:09 INFO routes.py product[line:120] Successfully query
2021-12-20 15:13:33 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:14:10 INFO routes.py checkout[line:258] Successfully added information to info table
2021-12-20 15:14:11 INFO routes.py checkout[line:269] Successfully added product to cart_item table
2021-12-20 15:14:11 INFO routes.py checkout[line:276] Successfully delete product from cart table
2021-12-20 15:14:11 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:14:22 INFO routes.py logout[line:344] logout
2021-12-20 15:14:22 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:14:35 INFO routes.py login[line:64] 321 login
2021-12-20 15:14:43 INFO routes.py agree[line:495] Agree to user return
2021-12-20 15:14:44 INFO routes.py reject[line:506] Refusal to return a product to a user
2021-12-20 15:15:06 INFO routes.py seller_add[line:442] seller add the product
2021-12-20 15:16:14 INFO routes.py seller_edit[line:414] seller edit the product
2021-12-20 15:16:14 INFO routes.py seller_edit[line:415] Successful modification of database information
2021-12-20 15:22:21 INFO routes.py seller_delete[line:395] seller delete the product
2021-12-20 15:22:21 INFO routes.py logout[line:344] logout
2021-12-20 15:22:21 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:22:21 INFO routes.py register[line:25] User try to sign up
2021-12-20 15:22:21 INFO routes.py register[line:25] User try to sign up
2021-12-20 15:22:21 INFO routes.py logout[line:344] logout
2021-12-20 15:22:21 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:22:21 INFO routes.py register[line:25] User try to sign up
2021-12-20 15:22:21 INFO routes.py register[line:25] User try to sign up
2021-12-20 15:22:21 INFO routes.py logout[line:344] logout
2021-12-20 15:22:21 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:22:21 INFO routes.py register[line:25] User try to sign up
2021-12-20 15:22:21 INFO routes.py register[line:25] User try to sign up
2021-12-20 15:23:39 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:24:01 INFO routes.py logout[line:344] logout
2021-12-20 15:24:01 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:24:07 INFO routes.py category[line:98] category items
2021-12-20 15:24:09 INFO routes.py product[line:115] Successfully query Kyrie 7
2021-12-20 15:24:09 INFO routes.py product[line:120] Successfully query
2021-12-20 15:24:18 INFO routes.py product[line:115] Successfully query Kyrie 7
2021-12-20 15:24:18 INFO routes.py product[line:120] Successfully query
2021-12-20 15:25:27 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:25:27 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:25:41 INFO routes.py login[line:67] 12 login
2021-12-20 15:25:41 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:25:46 INFO routes.py category[line:98] category items
2021-12-20 15:25:48 INFO routes.py product[line:115] Successfully query test
2021-12-20 15:25:48 INFO routes.py product[line:120] Successfully query
2021-12-20 15:25:51 INFO routes.py product[line:115] Successfully query test
2021-12-20 15:25:51 INFO routes.py product[line:120] Successfully query
2021-12-20 15:25:51 INFO routes.py product[line:125] 12 add products
2021-12-20 15:25:51 INFO routes.py product[line:135] Successfully added items to cart table
2021-12-20 15:25:51 INFO routes.py product[line:142] 12 add product to shopping cart successfully
2021-12-20 15:26:02 INFO routes.py checkout[line:258] Successfully added information to info table
2021-12-20 15:26:02 INFO routes.py checkout[line:269] Successfully added product to cart_item table
2021-12-20 15:26:02 INFO routes.py checkout[line:276] Successfully delete product from cart table
2021-12-20 15:26:02 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:29:06 INFO routes.py logout[line:344] logout
2021-12-20 15:29:06 INFO routes.py home[line:16] Enter the home page
2021-12-20 15:29:21 INFO routes.py login[line:64] 321 login
2021-12-20 15:29:28 INFO routes.py seller_delete[line:395] seller delete the product
